[target.xtensa-esp32s3-none-elf]
runner = "probe-rs run --chip=esp32s3 --always-print-stacktrace --no-location --catch-hardfault"

[env]
DEFMT_LOG = "debug"

[build]
rustflags = [
  "-C", "link-arg=-Tlinkall.x",
  "-C", "link-arg=-Tdefmt.x",
  "-C", "link-arg=-nostartfiles",
]

target = "xtensa-esp32s3-none-elf"

[unstable]
build-std = ["core"]
