name: dummy-button-gergers

on:
  pull_request:
    paths:
    - 'dummy-button/*.kicad_sch'
    - 'dummy-button/*.kicad_pcb'
    - 'dummy-button/*.kibot.yaml'
    - '.github/workflows/dummy-button-jlcpcb.yaml'
  workflow_dispatch:
    inputs:
      name:
        description: 'Workflow run name'
        required: false
        default: 'Dummy button gerbers'
  
jobs:
  jlcpcb:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: INTI-CMNB/KiBot@v2_k9
      with:
        config: jlcpcb.kibot.yaml
        dir: output
        schema: 'dummy-button/dummy-button.kicad_sch'
        board: 'dummy-button/dummy-button.kicad_pcb'
    - name: 'Cleanup build folder'
      run: sudo rm -rf ./output/tmp
    - name: 'Upload results'
      uses: actions/upload-artifact@v4
      with:
        name: dummy-button-jlcpcb
        path: output
